# This is a basic workflow to help you get started with Actions

name: build-wwiser

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
    paths: # Only run on code change
    - "wwiser/**/*.py"
    - "wwiser.py"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "dist"
  release-new-version:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get Release Version
        id: release_version
        run: |
          $DateString = Get-Date -Format "yyyyMMdd"
          echo "wwiser_version=$DateString" >> $env:GITHUB_OUTPUT
            
      - name: Build WWiser
        env:
          wwiser_version: ${{ steps.release_version.outputs.wwiser_version }}
        run: python build.py ${{ env.wwiser_version }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/wwiser.pyz
          name: ${{ env.WWISER_VERSION}}
          tag_name: ${{env.WWISER_VERSION}}
        env:
          WWISER_VERSION: v${{ steps.release_version.outputs.wwiser_version }}
